classdef HTMLDatabaseAnalysisWriter < HTMLDataTableWriter

    properties
        outputFieldDfd
        da
        useImageExtensionList = {'png', 'svg', 'jpg'};
    end

    methods
        function html = HTMLDatabaseAnalysisWriter(varargin)
            html = html@HTMLDataTableWriter(varargin{:});
            html.outputFieldDfd = OutputField();
        end
        
        function buildValueStruct(html)
            % need to additionally request output field since its not
            % displayable
            buildValueStruct@HTMLDataTableWriter(html, 'extraFields', {'output'});

            fieldNames = fieldnames(html.valueStruct);
            [~, origIdx] = setdiff(fieldNames, {'index', 'runTimestamp', 'success', 'figureInfo', 'output', 'exception'});
            fieldNames = makecol(fieldNames(sort(origIdx)));
            html.fields = [{'index'; 'success'; 'figures'; 'output'}; fieldNames; {'runTimestamp'}];
            
            html.valueStruct = assignIntoStructArray(html.valueStruct, 'exception', ...
                html.table.getValues('exception'));
            html.valueStruct = assignIntoStructArray(html.valueStruct, 'figureInfo', ...
                html.table.getValues('figureInfo'));
        end

        function str = getTooltipForField(html, field)
            if strcmp(field, 'success')
                str = 'Analysis ran successfuly on this entry?';
            elseif strcmp(field, 'figures')
                str = 'View figures generated by the analysis';
            elseif strcmp(field, 'output')
                str = 'Output generated for this entry';
            elseif strcmp(field, 'runTimestamp')
                str = 'Analysis timestamp for this entry';
            else
                str = getTooltipForField@HTMLDataTableWriter(html, field);
            end
        end

        function buildColumnAttrMap(html)
            buildColumnAttrMap@HTMLDataTableWriter(html);
            indexColumnAttr = {'style', sprintf('background-color: %s;', ...
                html.indexColumnBackground)};
            html.columnAttrMap('success') = indexColumnAttr;
            html.columnAttrMap('figures') = indexColumnAttr; 
            html.columnAttrMap('output') = indexColumnAttr; 
            html.columnAttrMap('runTimestamp') = indexColumnAttr; 
        end

        function writeEntryRow(html, entry)
            fields = html.fields;

            index = str2num(entry.index);
            success = entry.success;
            exception = entry.exception;
            entryRowId = sprintf('row%d', index);
            figureRowId = sprintf('figureRow%d', index);
            outputRowId = sprintf('outputRow%d', index);

            figureInfo = entry.figureInfo;
            nFigures = length(figureInfo);

            % color row red if error
            if isfield(entry, 'success') && strcmp(entry.success, '0')
                html.openTableRow('class', 'error', 'id', entryRowId); 
            else
                html.openTableRow('id', entryRowId);
            end

            for iField = 1:length(fields)
                field = fields{iField};

                % color table cells depending on the field type
                if html.columnAttrMap.isKey(field)
                    extras = html.columnAttrMap(field);
                    if ~iscell(extras)
                        extras = {extras};
                    end
                else
                    extras = {};
                end

                html.openTableCell(extras{:});
                if strcmp(field, 'success')
                    % entry.success will be '0' or '1' as it has been converted to string
                    if strcmp(success, '1')
                        contents = '<span class="label">Success</span>';
                    else
                        contents = ['<span class="label label-important">Error</span>'];
                    end
                    html.writeTag('div', contents); 

                elseif strcmp(field, 'figures')
                    if nFigures > 0
                        % put button that toggles figureRow tr open and closed
                        html.openTag('div')
                        buttonText = sprintf('%d Figures', nFigures);
                        buttonClick = sprintf('toggle_%s()', figureRowId);
                        html.writeTag('button', buttonText, 'type', 'button', ...
                            'class', 'btn btn-mini', 'data-toggle', 'button', ...
                            'onclick', buttonClick);
                        html.closeTag('div');
                    else
                        contents = '';
                        html.writeTag('div', contents, 'class', 'ellipsis'); 
                    end

                elseif strcmp(field, 'output')
                    html.openTag('div')
                    output = entry.output;
                   
                    nLines = html.outputFieldDfd.getLineCounts(output);
                   
                    buttonText = sprintf('%d Lines', nLines);
                    buttonClick = sprintf('$(''#%s'').toggle()', outputRowId);
                    html.writeTag('button', buttonText, 'type', 'button', ...
                        'class', 'btn btn-mini', 'data-toggle', 'button', ...
                        'onclick', buttonClick);
                    html.closeTag('div');

                else
                    contents = ansiToHtml(entry.(field));
                    html.writeTag('div', contents, 'class', 'ellipsis'); 
                end
                html.closeTableCell();
            end

            html.closeTableRow();

            html.writeFigureCarouselRow(entry, entryRowId, figureRowId);
            html.writeOutputRow(entry, outputRowId);
        end

        function writeFigureCarouselRow(html, entry, entryRowId, figureRowId)
            index = str2num(entry.index);
            figureInfo = entry.figureInfo;
            nFigures = length(figureInfo);
            
            % write tr full of figures into a script
            if nFigures > 0
                % rather than write the figure row tr directly, we write a javascript
                % function for inserting the tr row when asked. This prevents the html page
                % from loading all figures simultaneously
                figureCarouselId = sprintf('figureCarousel%d', index);
                html.openTag('script', 'type', 'text/javascript');
                html.inString = true;
                html.fprintf('function toggle_%s() {\n', figureRowId);

                figureSelector = sprintf('$(''#%s'')', figureRowId);
                entrySelector = sprintf('$(''#%s'')', entryRowId);
                % figure out if the row exists
                html.fprintf('if(%s.length > 0) {\n', figureSelector);
                % delete to close
                html.fprintf('%s.remove();\n', figureSelector);
                html.fprintf('} else {\n');
                % create to open
                html.fprintf('%s.after("', entrySelector);

                html.openTableRow('class', 'figureRow', 'id', figureRowId);
                html.openTag('td', 'colspan', '100%', 'class', 'figures');
                
                html.openTag('div', 'id', figureCarouselId, 'class', 'figureCarousel carousel slide');
                html.openTag('div', 'class', 'carousel-inner figureCarouselInner' );

                analysisPath = html.da.pathAnalysis;

                extList = html.useImageExtensionList;
                for i = 1:nFigures
                    info = figureInfo(i);
                    [hasExt extLoc] = ismember(extList, info.extensions);
                    extIdx = extLoc(find(hasExt,1, 'first'));
                    if isempty(extIdx)
                        % use one of the extensions provided and hope for the best
                        extIdx = 1;
                    end
                    ext = info.extensions{extIdx};

                    % this will be the absolute path to the figure
                    figFullFileName = info.fileLinkList{extIdx};
                    % get the path of the figure relative to the analysis path
                    figRelativePath = relativepath(figFullFileName, analysisPath, ...
                        'dropDotSlash', true, 'dropTrailingSlash', true);
                    figUrl = [figRelativePath];

                    figName = info.name;
                    figCaption = info.caption;
                    figWidth = info.width;
                    figHeight = info.height;
                    viewportWidth = 950;

                    if i == 1
                        html.openTag('div', 'class', 'active item');
                    else
                        html.openTag('div', 'class', 'item');
                    end
                    %html.openTag('li');
                    %html.openTag('div', 'class', 'thumbnail');

                    % centered container
                    html.openTag('div', 'class', 'figureWrapper', 'style', sprintf('width: %dpx;', viewportWidth));

                    if strcmp(ext, 'svg')
                        svgId = sprintf('figure%d-%d', index, i);
                        html.embedSVG('url', figUrl, 'viewportWidth', viewportWidth, 'width', figWidth, ...
                            'height', figHeight', 'alt', figName);
                    else
                        html.writeTag('img', '', 'src', figUrl, 'alt', figName); 
                    end

                    html.openTag('div', 'class', 'figureCaption', 'style', sprintf('width: %dpx;', figWidth));
                    html.writeTag('h3', figName);
                    html.writeTag('p', figCaption);

                    html.openTag('p');
                    %html.writeTag('span', '', 'class', 'icon-download');
                    for iExt = 1:length(info.extensions)
                        ext = info.extensions{iExt};
                        
                        % this will be the absolute path to the figure
                        figFullFileName = info.fileLinkList{iExt};
                        % get the path of the figure relative to the analysis path
                        figRelativePath = relativepath(figFullFileName, analysisPath, ...
                            'dropDotSlash', true, 'dropTrailingSlash', true);
                        url = [figRelativePath];

                        html.openTag('a', 'href', url, 'target', '_blank');
                        html.writeTag('small', ext);
                        html.closeTag('a');
                        html.fprintf('&nbsp;');
                    end
                    html.closeTag('p');
                    html.closeTag('div');

                    html.closeTag('div');
                    html.closeTag('div');

                    %html.closeTag('div');
                    %html.closeTag('li');
                end
                html.closeTag('div');

                if nFigures > 1
                    html.writeTag('a', '&lsaquo;', 'class', 'carousel-arrow carousel-control left', ...
                        'href', ['#' figureCarouselId], 'data-slide', 'prev');
                    html.writeTag('a', '&rsaquo;', 'class', 'carousel-arrow carousel-control right', ...
                        'href', ['#' figureCarouselId], 'data-slide', 'next');
                end
                html.closeTag('div');
                html.closeTableRow();

                html.fprintf('");\n');
                % activate the carousel
                html.fprintf('$("#%s").carousel({interval: false});', figureCarouselId);

                % activate the svgpan
                html.fprintf('$("#%s svg").svgPan("viewport");', figureRowId);

                % end if and function
                html.fprintf('}\n}\n');
                html.inString = false;
                html.closeTag('script');
            end
        end

        function writeOutputRow(html, entry, outputRowId)
            index = str2num(entry.index);
            output = entry.output;
            
            % write tr full of output text 
            html.openTableRow('class', 'outputRow', 'id', outputRowId);
            html.openTag('td', 'colspan', '100%', 'class', 'output');

            html.openTag('div', 'class', 'outputWrapper');

            % print an alert with either success or the exception details
            if strcmp(entry.success, '1')
                html.openTag('div', 'class', 'alert alert-success');
                html.writeTag('strong', 'Success!');
                html.fprintf(' Analysis %s ran successfully on this %s entry', ...
                    html.da.getName(), html.da.getMapsEntryName());
                html.closeTag('div');
            else
                exc = html.table(index).getValue('exception');
                if isempty(exc)
                    warning('Exception field not loaded when writing DatabaseAnalysisResultsTable');
                    func = '';
                    line = NaN;
                    msg = '';
                else
                    func = exc.stack(1).name;
                    line = exc.stack(1).line;
                    msg = exc.message;
                end
    
                html.openTag('div', 'class', 'alert alert-error');
                html.openTag('p');
                html.writeTag('strong', 'Error!');
                html.fprintf(' Analysis %s threw an exception:', html.da.getName());
                html.writeTag('p', sprintf('<tt>%s</tt> at line <tt>%d</tt>', ...
                     func, line));
                html.openTag('p');
                html.writeTag('tt', msg);
                html.closeTag('p');
                html.closeTag('div');
            end

            html.writeTag('pre', ansiToHtml(output), 'class', 'linenums pre-scrollable');
            html.closeTag('div');

            html.closeTag('td');
            html.closeTableRow();
        end

        function embedSVG(html, varargin)
            %html.writeTag('image', '', 'width', '100%', 'height', sprintf('%dpx', height), ...
            %    'src', url, 'alt', alt); 
            %html.writeTag('image', '', 'src', url, 'alt', alt); 
            %
            %html.writeTag('object', '', 'id', id, 'height', '400', 'type', 'image/svg+xml', 'data', url);  
            p = inputParser;
            p.addParamValue('viewportWidth', 950, @isnumeric)
            p.addParamValue('width', 500, @isnumeric);
            p.addParamValue('height', 400, @isnumeric);
            p.addParamValue('url', '', @ischar);
            p.addParamValue('alt', '', @ischar);
            p.parse(varargin{:});

            viewportWidth = p.Results.viewportWidth;
            width = p.Results.width;
            height = p.Results.height;

            imageX = num2str(round((viewportWidth - width) / 2));

            url = p.Results.url;
            alt = p.Results.alt;
            html.openTag('svg', 'alt', alt, 'width', num2str(viewportWidth), ...
                'height', num2str(height), ...
                'xmlns', 'http://www.w3.org/2000/svg', ...
                'xlink', 'http://www.w3.org/1999/xlink');
            html.openTag('g', 'id', 'viewport');
            html.writeTag('image', '', 'x', num2str(imageX), 'y', '0', ...
                'width', num2str(width), ...
                'height', num2str(height), 'xlink:href', url);
            html.closeTag('g');
            html.closeTag('svg');
        end

        function generate(html, da)
            html.da = da;
            desc = da.getDescriptionParam();
            html.table = da.resultTable;

            % generate report options
            name = da.getName();
            entryName = da.getMapsEntryName();
            html.pageTitle = name;
            html.mainHeader = html.table.entryNamePlural; 
            html.subHeader = sprintf('DatabaseAnalysis run on %s with %d entries.<br/><strong>Run Description</strong>: %s<br/><strong>Parameters</strong>: %s <br/><br/>', ...
                entryName, html.table.nEntries, da.runDescription, desc);
            html.navTitle = 'Database Analysis';
            html.navSubTitle = name;

            html.openFile();
            html.writeHeader();

            html.writeDataTable();

            html.writeFooter();
            html.closeFile();

            html.copyResources();
        end

    end
end

